### ISSUE TITLE
Tuning `robot_localization`

### ISSUE THREAD

**Issue by manglemix** [utahrobotics/lunadev-2024#4]
`robot_localization` is a very useful implementation of Kalman Filters that can take in multiple streams of data from sensors and outputs a pretty good estimate of where the robot is. For example, the realsense camera has an IMU, and the pozyx also has an IMU on top of its ability to estimate position relative to its tags. We are also planning to add wheel encoders (which track how far our wheels have spun). These 4 sources of data are fed into `robot_localization` and it does a lot of math to average out where the robot is.

The problem is that accuracy is not free. There is a lot of tuning to be done in configuration files ([Documentation can be found here](https://docs.ros.org/en/noetic/api/robot_localization/html/configuring_robot_localization.html)). One of the main parameters that we must tune and can provide the best benefits immediately are the covariance matrices. These are configured in the `Positioning` node for Pozyx, and the `rs_launch.py` for the realsense camera. Covariance matrices measure how inaccurate a measurement is. For example, the realsense camera has a default covariance of 0.01 for each axis of angular velocity. We need to check if this is accurate as the camera is not exactly new. Right now, our `Positioning` node has a default covariance of 0 for every possible measurement that Pozyx can produce. This is extremely wrong as it suggests that Pozyx is 100% accurate.

Ideally, we would spend time in the lab collecting samples from these sensors and empirically determine what the covariance matrices are. We should also cross-reference these with numbers we can find online. This work is extremely important for 2 reasons:

1. We need to make sure that our robot knows where it is so that it knows how far it needs to drive to reach the excavation or construction sites
2. We are not allowed to use the walls as guides, so our code needs to eliminate walls from our list of identified obstacles. Our camera will definitely be able to identify the walls as obstacles. We can't just eliminate any obstacle we see as some obstacles could be valid, such as craters. So to know if an obstacle is a wall, we need to know where it is. Since the position of obstacles are always relative to the camera, we need to know where the camera is!

**Comment by Micah-Ribbens** [comment]
There is a lot of slipping because there is very fine dust. So dead reckoning may not work. Accelerators should help up with that slipping. The robot has 360 degrees of view in theory. We should be constantly updating the april tags. The april tags will be on the leftmost and bottommost corner of the map. The april tag detection should be very accurate.
